### ISSUE TITLE
Convert input file resource to data source

### ISSUE THREAD

**Issue by honkyjive** [ahzhezhe/terraform-generator#1]
hey i'm trying to import an existing terraform file so I can do some manipulation on it dynamically using your library.

I'm trying to understand this import:
`import { vpc as vpcDS } from 'other-terraform-project';`

can you be more specific with how the `'other-terraform-project'` is supposed to work? 

Currently, I used your cidr example to generate a `output/dev/subnets/terraform.tf` file and I have another ts that is trying to import that generated file

```
fs.readFile(path.join('input', configs.env, 'subnets', "terraform.tf"), (err, data) => {
  if (err) throw err;
  console.log(data.toString());
  tfg.dataFromResource(data.toString(), null, ['cidr_block', ['tags', 'tag']]);
})
```

It is failing the first argument in the function `dataFromResource` which is type resource. I'm using a string. So it makes sense to me that it is failing. 

Is this possible?

**Comment by ahzhezhe** [comment]
`dataFromResource` is not to transform .tf file, it is to transform terraform-generator's `resource` object to a `data` object.

Example:

**vpc.ts**
```typescript
import TerraformGenerator from 'terraform-generator';

const tfg = new TerraformGenerator({ version: '0.12' });

tfg.provider('aws', {
  region: 'ap-southeast-1'
});

const vpc = tfg.resource('aws_vpc', 'default', {
  cidr_block: '172.88.96.0/19'
});

tfg.write();

export { vpc };
```

**Result of vpc.ts**
```typescript
provider "aws" {
  region = "ap-southeast-1"
}

resource "aws_vpc" "default" {
  cidr_block = "172.88.96.0/19"
}
```

**subnet.ts**
```typescript
import TerraformGenerator from 'terraform-generator';
import { vpc as vpcDS } from './vpc';

const tfg = new TerraformGenerator({ version: '0.12' });

tfg.provider('aws', {
  region: 'ap-southeast-1'
});

const vpc = tfg.dataFromResource(vpcDS, null, ['cidr_block']);

tfg.resource('aws_subnet', 'default', {
  vpc_id: vpc.attr('id'),
  cidr_block: '172.88.96.0/22'
});

tfg.write();
```

**Result of subnet.ts**
```typescript
provider "aws" {
  region = "ap-southeast-1"
}

data "aws_vpc" "default" {
  cidr_block = "172.88.96.0/19"
}

resource "aws_subnet" "default" {
  vpc_id            = data.aws_vpc.default.id
  cidr_block        = "172.88.96.0/22"
}
```

Hope it makes sense.
