### ISSUE TITLE
Terraform Configuration is failing when provisioner added to resource

### ISSUE THREAD

**Issue by arkrishna1986** [ahzhezhe/terraform-generator#10]
**Describe the bug**
Terraform Configuration is failing when provisioner added to resource

**To reproduce**
1.Add provisioner to resource based on terraform doc
2.try to create terraform config

My code:
```javascript
tfg.resource("aws_instance","example",{
  ami:"ami-042b34111b1289ccd",
  instance_type:"t2.micro"
},tfg.provisioner("local-exec",{
    command:"echo The server's IP address is self.private_ip"
  })
);
```

Error response:
____________________________________________________________
node_modules/terraform-generator/dist/blocks/Block.js:90
this.innerBlocks.forEach(block => {
                         ^

TypeError: this.innerBlocks.forEach is not a function
______________________________________________________

**Expected behavior**
Terraform configuration should create without any issues

**Additional context**

**Comment by ahzhezhe** [comment]
Please change your code to this:

```javascript
tfg.resource('aws_instance', 'example', {
  ami: 'ami-042b34111b1289ccd',
  instance_type: 't2.micro'
}, [
  new Provisioner('local-exec', {
    command: "echo The server's IP address is self.private_ip"
  })
]);
```

**Comment by arkrishna1986** [comment]
Thanks for your quick response..it worked.

Much Appreciated..!!

Regards
R
