### ISSUE TITLE
Interpolation-only expressions being  deprecated

### ISSUE THREAD

**Issue by andrewmcallister** [ahzhezhe/terraform-generator#11]
**Describe the bug**
Perhaps I am missing something but no matter what I try, I cannot get terraform generator to generate Arrays without double quotes for  Interpolation-only expressions being  deprecated.  The terraform-generator module seems to indicate support for current version of terraform.  Is this supported?

**To reproduce**
```
const gobject = new String(`okta_group.group_${objName}.id`)
groupArray.push(`${gobject}`)

tfg.resource('okta_group_rule', `rule_${objName}`, {
  name: `${record.name}`,
  status: "ACTIVE",
  group_assignments: groupArray,
  expression_type: record.conditions.expression.type,
  expression_value: record.conditions.expression.value
});
```

groupArray will appear as 

```
resource "okta_group_rule" "rule_deptSecurity" {
  name   = "dept: Security"
  status = "ACTIVE"
  group_assignments = [
    "okta_group.group_Security.id"
  ]
  expression_type  = "urn:okta:expression:1.0"
  expression_value = "user.department==\"Security\""
}
```

Logging to console shows no quotes but soon as generate resource using terraform-generator, quotes are added back.

**Expected behavior**
for newer versions of terraform, generate TF without the double quotes.

```
resource "okta_group_rule" "rule_deptSecurity" {
  name   = "dept: Security"
  status = "ACTIVE"
  group_assignments = [
    okta_group.group_Security.id
  ]
  expression_type  = "urn:okta:expression:1.0"
  expression_value = "user.department==\"Security\""
}
```

**Additional context**

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

**Comment by ahzhezhe** [comment]
The correct usage is

```
const gobject = new Argument(`okta_group.group_${objName}.id`);
groupArray.push(gobject);

tfg.resource('okta_group_rule', `rule_${objName}`, {
  name: `${record.name}`,
  status: 'ACTIVE',
  group_assignments: groupArray,
  expression_type: record.conditions.expression.type,
  expression_value: record.conditions.expression.value
});
```
