### ISSUE TITLE
Map values generated as blocks instead of variable assignment

### ISSUE THREAD

**Issue by EvanK** [ahzhezhe/terraform-generator#21]
**Describe the bug**

When adding variable values with `TerraformGenerator.addVars`, the generated tfvars do not format map types properly; they end up formatted as an object block instead.

**To reproduce**

An example in the console:
```bash
$ node
> const { TerraformGenerator } = require('terraform-generator');
> const tfg = new TerraformGenerator({ required_version: '>= 0.12' });
> tfg.addVars({ intval: 5432, strval: "whoop", listval: ["alpha", 'bravo', `charlie`], mapval: {key:"foo",key2:"bar"} });
> console.log(tfg.generate().tfvars)
intval = 5432

strval = "whoop"

listval = [
"alpha",
"bravo",
"charlie"
]

mapval {
key = "foo"
key2 = "bar"
}
```

**Expected behavior**
Would expect map values to be formatted as _a map assigned to a variable name_:

```terraform
// this is valid for tfvars definition
mapval = {
  key = "foo"
  key2 = "bar"
}
// this evidently is not
mapval {
  key = "foo"
  key2 = "bar"
}
```

**Additional context**

Using:
* Mac OS 10.15.7 (`Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64 i386`)
* Terraform v1.0.7
* nvm 0.36.0
* npm 6.14.13
* node v14.17.0
* terraform-generator 5.1.0

Thank you for this extremely useful npm module!

**Comment by ahzhezhe** [comment]
Please use map function or Map class for terraform map property

```
tfg.addVars({
  intval: 5432,
  strval: 'whoop',
  listval: ['alpha', 'bravo', 'charlie'],
  mapval: map({ key: 'foo', key2: 'bar' })
});
```

https://ahzhezhe.github.io/docs/terraform-generator-v5/modules.html#map
