### ISSUE TITLE
variable types are no longer supported with double quotes from terraform.

### ISSUE THREAD

**Issue by kyriakosdem** [ahzhezhe/terraform-generator#24]
When defining a variable like the below:
`tfg.variable("region", { type: 'string' });`

The output in the file generated is:
`variable "region" {
type = "string"
}`

The problem here is that with the latest terraform update it is expecting the type value to be without the double quotes (ex. instead of type=**"string"** => type=**string**) hence when executing terraform, it failing.

Similar issue (not blocking from terraform yet but with warnings) is happening also to the resources. For example when you define ${data.api_gatewayv2_api.myresource.id} as a value for a field, the output will create the file with quotes again `field = "data.api_gatewayv2_api.myresource.id"` and terraform is complaining again about the quotes.

**Comment by ahzhezhe** [comment]
The actual syntax for your first issue is:

```
tfg.variable('region', {
  type: arg('string')
});
```

For second issue:

```
const myresource_data = tfg.data('api_gatewayv2_api', 'myresource', {
  key: 'value'
});

tfg.resource('resource_type', 'resource_name', {
  api_gateway_id: myresource_data.id
});
```

**Comment by ahzhezhe** [comment]
Just to add on that I don't really use terraform variable in my project, I will just put my variables in a more Javascript way, in a .js file, .json file or .env file
