### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by jeremysquires-sensorup** [ahzhezhe/terraform-generator#26]
Ability to add comments to generated code, such as "DO NOT EDIT THIS FILE IT IS GENERATED" would be very useful

Yes, we are adding comments externally through shell scripts, which is less than ideal.

**Comment by ahzhezhe** [comment]
It is added in v5.2.0

example:
`
tfg.comment('DO NOT EDIT THIS FILE IT IS GENERATED');
`

**Comment by jeremysquires-sensorup** [comment]
Excellent! Thanks for the fast turnaround!
