### ISSUE TITLE
Feature request: Is a read file possible to modify existing configurations?

### ISSUE THREAD

**Issue by vanvuongngo** [ahzhezhe/terraform-generator#29]
**Is your feature request related to a problem? Please describe.**
As I understood this library allows to generator new configurations.
How about extending existing configurations?
I guess it needs a read feature or is it already possible?

**Comment by ahzhezhe** [comment]
Are you asking about reading existing tf file and convert it to javascript code?

**Comment by vanvuongngo** [comment]
Yes, I am thinking about to create a CLI to read existing tf file and modify it with your library.
