### ISSUE TITLE
bad variable type translation

### ISSUE THREAD

**Issue by gregory** [ahzhezhe/terraform-generator#6]
**Describe the bug**

```tf
  const pass = tf.variable('config', {
    type: [new Map({key:'string', val: 'string'})], default: [{key:'some',val:'default'}]
  }, [{key:'ex', val:'pass'}))
```
translates to: 
```
variable "config" {
  type = [
    {
      key = "string"
      val = "string"
    }
  ]
  default {
    key = "some"
    val = "default"
  }
}
```

I tried to put it within quotes, but then terraform failed with: 
```
19, in variable "config":
  19:   type = "list(object({ key  = string val = string }))"

The legacy variable type hint form, using a quoted string, allows only the
values "string", "list", and "map". To provide a full type expression, remove
the surrounding quotes and give the type expression directly.

```
which seems to point to a possible bug with type "number" ... 
**To reproduce**
```tf
  const pass = tf.variable('config', {
    type: [new Map({key:'string', val: 'string'})], default: [{key:'some',val:'default'}]
  }, [{key:'ex', val:'pass'}))
console.log(tf.generate().tf)
```

**Expected behavior**
should print: 
```tf
variable "config" {
  type = list(object({key = string val = string }))
  default = [{key:'some',val:'default'}]
}
```

**Comment by ahzhezhe** [comment]
List, Set, Tuple & Object types are now available in version 4.5.0.

List, Set & Tuple are actually identical.
Object is identical to Map.

The reason why they were not there before is because I don't see a use case for complex terraform variable, since you are using JS/TS already, isn't putting these variables in JS/TS more appropriate and easier to maintain?

To achieve what you are trying to do in version 4.5.0:
```javascript
tfg.variable('config', {
  type: arg(`list(object({
    key = string
    val = string
  }))`),
  default: list({
    key: 'some',
    val: 'default'
  })
}, list({
  key: 'ex',
  val: 'pass'
}));
```

Let me know if the issue is not addressed, thanks.

**Comment by gregory** [comment]
I was evaluating the library before using it in our project & noticed this was missing :) 
Thanks for building this, super helpful! 

NOTE: For the record, it would have to be: 
```tf
tfg.variable('config', {
  type: arg(`list(object({
    key = string
    val = string
  }))`),
  default: [{
    key: 'some',
    val: 'default'
  }]
}, [{
  key: 'ex',
  val: 'pass'
}])

```

**Comment by gregory** [comment]
@ahzhezhe I'm going to reopen this issue as I found another similar issue. Great job with the lib btw, I'm trying to script our terraform files and this comes in handy! 

```js
const ta = {tags:{FOO:'bar'}}
tf.resource('aws_ecs_cluster', 'bar', {
  ...ta,
  name:'bar'
})
```

is going to print: 
```tf
resource "aws_ecs_cluster" "bar" {
  tags {
    FOO = "bar"
  }
  name = "bar"
}
```

instead of(note the `tags =`): 
```tf
resource "aws_ecs_cluster" "bar" {
  tags ={
    FOO = "bar"
  }
  name = "bar"
}
```

Let me know if there is some magic function that I missed in the doc to solve this :) 

cheers, 
G.

**Comment by ahzhezhe** [comment]
Yes, indeed you missed out map function.

```javascript
const ta = {
  tags: map({
    FOO: 'bar'
  })
};
tfg.resource('aws_ecs_cluster', 'bar', {
  ...ta,
  name: 'bar'
});
```

**Comment by ahzhezhe** [comment]
You should take a good look at this section:
https://github.com/ahzhezhe/terraform-generator#arguments
