### ISSUE TITLE
Import is not working by Readme manual

### ISSUE THREAD

**Issue by dlifanov** [ahzhezhe/terraform-generator#7]
**Describe the bug**
import TerraformGenerator, { Resource, map, fn } from 'terraform-generator';
^^^^^^

SyntaxError: Cannot use import statement outside a module
**To reproduce**
Follow Readme instructions
**Expected behavior**
Import completes successfully

**Additional context**
Tried to rename the file from .js to .mjs
Tried to add "type": "module" to package.json
Tried to add parameter --experimental-modules from cli
Node v12.14.1

**Comment by ahzhezhe** [comment]
Sample code in README is ES6 code.

Without ES6, you can do this:

```javascript
const TFG = require('terraform-generator');
const { default: TerraformGenerator, map } = TFG;

const tfg = new TerraformGenerator();

tfg.resource('example', 'example', {
  tags: map({
    name: 'example'
  })
});
```
