### ISSUE TITLE
Repeated blocks

### ISSUE THREAD

**Issue by gvisca** [ahzhezhe/terraform-generator#8]
**Describe the bug**
I would like to create an s3 bucket with multiple cors blocks
```
resource "aws_s3_bucket" "my-bucket" {
  bucket = "my-bucket"
  cors_rule {
    allowed_headers = [
      "Authorization",
    ]
    allowed_methods = [
      "GET",
    ]
    allowed_origins = [
      "*",
    ]
    expose_headers  = []
    max_age_seconds = 3000
  }
  cors_rule {
    allowed_headers = [
      "*",
    ]
    allowed_methods = [
      "PUT",
    ]
    allowed_origins = [
      "*",
    ]
    expose_headers  = []
    max_age_seconds = 0
  }
```
**To reproduce**
```
tfg.resource("aws_s3_bucket", "my-bucket", {
    bucket: "my-bucket",
    
    cors_rule: {
        allowed_headers: ["*"],
        allowed_methods: ["PUT"],
        allowed_origins: ["*"],
        expose_headers: [],
        max_age_seconds: 0,
    },
    cors_rule: {
        allowed_headers: ["Authorization"],
        allowed_methods: ["GET"],
        allowed_origins: ["*"],
        expose_headers: [],
        max_age_seconds: 3000,
    }
})
```
**Expected behavior**
This only creates 1 block

**Additional context**

**Comment by ahzhezhe** [comment]
What you wrote is not even a valid Javascript.

Put them in array:
```javascript
tfg.resource('aws_s3_bucket', 'my-bucket', {
  bucket: 'my-bucket',
  cors_rule: [
    {
      allowed_headers: ['*'],
      allowed_methods: ['PUT'],
      allowed_origins: ['*'],
      expose_headers: [],
      max_age_seconds: 0
    },
    {
      allowed_headers: ['Authorization'],
      allowed_methods: ['GET'],
      allowed_origins: ['*'],
      expose_headers: [],
      max_age_seconds: 3000
    }
  ]
});
`

**Comment by gvisca** [comment]
Of course 🤣
I didn't find a way to make it work and it's sooooo simple

Thanks a lot for the tool, I love it !

**Comment by Striar-Yunis** [comment]
For those looking in the future the new way is:

```js
import { TerraformGenerator, list, map } from "terraform-generator";

const generator = new TerraformGenerator();
generator.resource("aws_s3_bucket", "my-bucket", {
  bucket: "my-bucket",
  cors_rule: list(
    {
      allowed_headers: ["*"],
      allowed_methods: ["PUT"],
      allowed_origins: ["*"],
      expose_headers: [],
      max_age_seconds: 0,
    },
    {
      allowed_headers: ["Authorization"],
      allowed_methods: ["GET"],
      allowed_origins: ["*"],
      expose_headers: [],
      max_age_seconds: 3000,
    }
  ),
});

generator.write();
```

**Comment by ahzhezhe** [comment]
Can you explain

> > What you wrote is not even a valid Javascript.
> > Put them in array:
> > ```js
> > tfg.resource('aws_s3_bucket', 'my-bucket', {
> >   bucket: 'my-bucket',
> >   cors_rule: [
> >     {
> >       allowed_headers: ['*'],
> >       allowed_methods: ['PUT'],
> >       allowed_origins: ['*'],
> >       expose_headers: [],
> >       max_age_seconds: 0
> >     },
> >     {
> >       allowed_headers: ['Authorization'],
> >       allowed_methods: ['GET'],
> >       allowed_origins: ['*'],
> >       expose_headers: [],
> >       max_age_seconds: 3000
> >     }
> >   ]
> > });
> > `
> > ```
> 
> This exact example fails on `6.4.2` on node 20.
> 
> ```js
> import { TerraformGenerator } from "terraform-generator";
> 
> const generator = new TerraformGenerator();
> generator.resource("aws_s3_bucket", "my-bucket", {
>   bucket: "my-bucket",
>   cors_rule: [
>     {
>       allowed_headers: ["*"],
>       allowed_methods: ["PUT"],
>       allowed_origins: ["*"],
>       expose_headers: [],
>       max_age_seconds: 0,
>     },
>     {
>       allowed_headers: ["Authorization"],
>       allowed_methods: ["GET"],
>       allowed_origins: ["*"],
>       expose_headers: [],
>       max_age_seconds: 3000,
>     },
>   ],
> });
> generator.write();
> 
> ------------------------------
> 
> resource "aws_s3_bucket" "my-bucket" {
>   bucket = "my-bucket"
>   cors_rule {
>     allowed_headers = [
>       "*"
>     ]
>     allowed_methods = [
>       "PUT"
>     ]
>     allowed_origins = [
>       "*"
>     ]
>     max_age_seconds = 0
>   }
>   cors_rule {
>     allowed_headers = [
>       "Authorization"
>     ]
>     allowed_methods = [
>       "GET"
>     ]
>     allowed_origins = [
>       "*"
>     ]
>     max_age_seconds = 3000
>   }
> }
> ```

Can you explain which part failed?
